---
sidebar: sidebar 
permalink: deploy-fsx-file-system.html 
keywords: vm workloads, deploy fsx, deploy storage for vms 
summary: Depois de verificar se o sistema de arquivos FSX for ONTAP recomendado, ou sistemas de arquivos, em alguns casos, atende aos seus requisitos exatos, você pode usar a fábrica de carga de trabalho para implantar o sistema em seu ambiente AWS. 
---
= Implante o sistema de arquivos FSX for ONTAP recomendado para cargas de trabalho da VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Depois de verificar se o sistema de arquivos FSX for ONTAP recomendado (ou vários sistemas de arquivos em alguns casos) atende aos seus requisitos exatos, você pode usar a fábrica de carga de trabalho para implantar o sistema em seu ambiente AWS.

Dependendo da política e das permissões adicionadas à sua conta do Workload Factory, você pode implantar o sistema de arquivos FSx para ONTAP completamente usando o Workload Factory (no modo de leitura/gravação). Se você tiver menos permissões (modo somente leitura) ou nenhuma permissão (modo Básico), precisará usar as informações do CloudFormation do Codebox e implantar o sistema de arquivos FSx para ONTAP na AWS.

.Requisitos para implantações no VMware Cloud na AWS
* Você precisa estar usando o VMware Cloud no AWS Software-Defined Data Center (SDDC) versão 1,20 ou superior para implantar o FSX para sistemas de arquivos ONTAP.
* Você não deve implantar o sistema de arquivos FSX for ONTAP na mesma VPC usada durante a implantação do SDDC. Em vez disso, você deve implantá-lo em uma nova Amazon VPC que você possui para habilitar a integração do VMware Cloud no AWS com o Amazon FSX for NetApp ONTAP.
* Você deve implantar o sistema de arquivos FSX for ONTAP na mesma região da AWS que o seu SDDC.


.Passos
. Na parte inferior da página *Plano de revisão*, selecione *implantar* e a página criar um sistema de arquivos FSX for ONTAP é exibida.
+
A maioria dos campos que definem seu sistema de arquivos FSX for ONTAP são preenchidos com base nas informações fornecidas, mas existem alguns campos que você precisa preencher nesta página.

+
Você pode usar a opção criação rápida ou criação avançada. Advanced Create oferece alguns parâmetros de armazenamento adicionais que você pode personalizar. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Veja o que essas duas opções oferecem"].

. * Credenciais da AWS*: Selecione ou adicione credenciais que darão à fábrica de carga de trabalho as permissões necessárias para criar seu sistema de arquivos FSX for ONTAP diretamente. Você também pode selecionar o código do CloudFormation no Codebox e implantar o sistema de arquivos FSX for ONTAP na AWS.
. *Nome do sistema de arquivos*: Digite o nome que você deseja usar para este sistema de arquivos FSX for ONTAP.
. *Tags*: Opcionalmente, você pode adicionar tags para categorizar este sistema de arquivos FSX for ONTAP.
. Na secção "rede e segurança", introduza as seguintes informações:
+
.. *Região e VPC*: Selecione a região e a VPC onde o sistema de arquivos FSX for ONTAP será implantado.
+
Se você estiver implantando no VMware Cloud na AWS, certifique-se de implantá-lo em uma VPC diferente da VPC onde o VMware Cloud on AWS é implantado.

.. *Grupo de segurança*: Ao usar a opção *criação avançada*, você pode selecionar o grupo de segurança padrão para a VPC do FSX for ONTAP para que todo o tráfego possa acessar o sistema de arquivos FSX for ONTAP.
+
Você pode adicionar uma regra de entrada que restringe o que outros serviços da AWS podem acessar o sistema de arquivos FSX for ONTAP. Isso bloqueará a quantidade de serviços que estão abertos. Estas são as portas e protocolos mínimos:

+
[cols="15,10,55"]
|===
| Protocolos | Portas | Finalidade 


| TCP, UDP | 111 | Portmapper (usado para negociar quais portas são usadas em solicitações NFS) 


| TCP, UDP | 635 | Mountd NFS (recebe solicitações de montagem NFS) 


| TCP, UDP | 2049 | Tráfego de rede NFS 


| TCP, UDP | 4045 | Gerenciador de bloqueio de rede (NLM, lockd) - lida com solicitações de bloqueio. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - notifica os clientes NFS sobre reinicializações do servidor para gerenciamento de bloqueio. 
|===
.. *Zona de disponibilidade*: Selecione a zona de disponibilidade e a sub-rede.
+
Você deve selecionar a mesma zona de disponibilidade em que o VMware SDDC é implantado se quiser evitar cobranças por tráfego entre zonas.

.. *Criptografia*: Ao usar a opção *Advanced Create*, você pode selecionar o nome da chave de criptografia AWS no menu suspenso.
.. *Controle de acesso de datastore*: Ao usar a opção *Advanced Create*, você pode selecionar se todos os hosts podem acessar os datastores ou se apenas certos nós de cluster do vSphere em uma sub-rede específica podem acessar os datastores.


. Na secção "Detalhes do sistema de ficheiros", introduza as seguintes informações:
+
.. *Credenciais ONTAP*: Insira e confirme a senha do ONTAP.
.. *Storage VM credentials* (somente criação avançada): Insira e confirme a senha da VM de armazenamento. A palavra-passe pode ser específica para este sistema de ficheiros ou pode utilizar a mesma palavra-passe introduzida para as credenciais ONTAP.


. Na seção *Resumo*, você pode visualizar o sistema de arquivos FSX for ONTAP e a configuração de datastore que o consultor de migração da VMware projetou com base em suas informações.
. Selecione *criar* para implantar o sistema de arquivos FSX for ONTAP. Este processo pode levar até 2 horas.
+
Opcionalmente, na janela Codebox você pode selecionar *Redirecionar para o CloudFormation* para criar o sistema de arquivos usando uma pilha do CloudFormation.

+
Em ambos os casos, você pode monitorar o progresso da criação no CloudFormation.



.Resultado
O sistema de arquivos FSX for ONTAP é implantado.
