---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: Depois de verificar se o sistema de arquivos FSx for ONTAP recomendado, ou sistemas de arquivos em alguns casos, atendem exatamente aos seus requisitos, você pode usar o Workload Factory para implantar o sistema no seu ambiente AWS. 
---
= Implante o sistema de arquivos FSX for ONTAP recomendado
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Depois de verificar se o sistema de arquivos FSx recomendado para ONTAP (ou vários sistemas de arquivos em alguns casos) atende exatamente aos seus requisitos, você pode usar o Workload Factory para implantar o sistema no seu ambiente AWS.

Dependendo da política e das permissões que você adicionou à sua conta do Workload Factory, você pode implantar o sistema de arquivos FSx para ONTAP completamente usando o Workload Factory (usando o modo de leitura/gravação).  Se você tiver menos permissões (modo somente leitura) ou nenhuma permissão (modo básico), será necessário usar o modelo CloudFormation do Codebox e implantar o sistema de arquivos FSx para ONTAP na AWS.



== Requisitos

* Você deve ter uma assinatura do Amazon Elastic VMware Service.
* Você deve ter as permissões necessárias para criar um sistema de arquivos FSx para ONTAP na sua conta da AWS.




== Considerações

* Você pode usar a opção criação rápida ou criação avançada. Advanced Create oferece alguns parâmetros de armazenamento adicionais que você pode personalizar. https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Veja o que essas duas opções oferecem"].
* Na seção "Preferências do Amazon Elastic VMware Service", você pode escolher o ambiente de virtualização do EVS para se conectar aos armazenamentos de dados externos.  Isso preenche automaticamente alguns campos com as opções de melhores práticas para a implantação.  Você pode alterar essas opções conforme necessário.




== Passos

. Na parte inferior da página *Plano de revisão*, selecione *implantar* e a página criar um sistema de arquivos FSX for ONTAP é exibida.
+
A maioria dos campos que definem seu sistema de arquivos FSX for ONTAP são preenchidos com base nas informações fornecidas, mas existem alguns campos que você precisa preencher nesta página.

. Na seção "Configuração geral do sistema de arquivos", insira as seguintes informações:
+
.. *Credenciais da AWS*: Selecione ou adicione credenciais que darão ao Workload Factory as permissões necessárias para criar seu sistema de arquivos FSx para ONTAP diretamente.  Você também pode selecionar o código do CloudFormation no Codebox e implantar o sistema de arquivos FSx para ONTAP na AWS.
.. *Nome do sistema de arquivos*: Digite o nome que você deseja usar para este sistema de arquivos FSX for ONTAP.
.. *Tags*: Opcionalmente, você pode adicionar tags para categorizar este FSx para o sistema de arquivos ONTAP.


. Na seção "Preferências do Amazon Elastic VMware Service", na lista "ID do ambiente", selecione o ambiente EVS ao qual os datastores serão conectados.
+
Isso preenche automaticamente os seguintes campos:

+
** *VPC*
** *Zona de Disponibilidade*
** *Sub-rede*
** Na seção *Acesso a Datastores NFS*, se você selecionou a opção *Somente gerenciamento de host EVS*, o campo *Gerenciamento de host EVS (CIDR)* será preenchido automaticamente.
** Na seção *Opções de montagem do datastore*, se você optou por montar datastores no cluster EVS, os campos *Endereço do VMware vCenter do cluster EVS* e *ARN secreto das credenciais do administrador do vSphere* serão preenchidos automaticamente.


. Na secção "rede e segurança", introduza as seguintes informações:
+
.. *Região e VPC*: Selecione a região e a VPC onde o sistema de arquivos FSx para ONTAP será implantado.
.. *Grupo de segurança* (somente criação avançada): Ao usar a opção *Criação avançada*, você pode selecionar o grupo de segurança padrão para a VPC FSx for ONTAP para que todo o tráfego possa acessar o sistema de arquivos FSx for ONTAP. Você pode criar um novo grupo de segurança ou selecionar um existente.
+
Se você habilitar a opção *Ajustar configuração do grupo de segurança para datastores EVS NFS*, o Workload Factory configurará o grupo de segurança de acordo com as configurações para datastores EVS NFS.

+
Você pode adicionar uma regra de entrada ao grupo de segurança que restrinja quais outros serviços da AWS podem acessar o sistema de arquivos FSx para ONTAP. Isso reduzirá o número de serviços abertos. Estas são as portas e protocolos mínimos:

+
[cols="15,10,55"]
|===
| Protocolos | Portas | Finalidade 


| TCP, UDP | 111 | Portmapper (usado para negociar quais portas são usadas em solicitações NFS) 


| TCP, UDP | 635 | Mountd NFS (recebe solicitações de montagem NFS) 


| TCP, UDP | 2049 | Tráfego de rede NFS 


| TCP, UDP | 4045 | Gerenciador de bloqueio de rede (NLM, lockd) - lida com solicitações de bloqueio. 


| TCP, UDP | 4046 | Network Status Monitor (NSM, statd) - notifica os clientes NFS sobre reinicializações do servidor para gerenciamento de bloqueio. 
|===
.. *Zona de disponibilidade*: Selecione a zona de disponibilidade e a sub-rede.
+
Você deve selecionar a mesma zona de disponibilidade em que o VMware SDDC é implantado se quiser evitar cobranças por tráfego entre zonas.

.. *Criptografia* (somente criação avançada): Ao usar a opção *Criação avançada*, você pode selecionar o nome da chave de criptografia da AWS no menu suspenso.
.. *Acesso aos datastores NFS* (somente criação avançada): Ao usar a opção *Criação avançada*, você pode selecionar se todos os hosts podem acessar os datastores ou se somente o host de gerenciamento do EVS pode acessá-los.


. Na secção "Detalhes do sistema de ficheiros", introduza as seguintes informações:
+
.. *Credenciais ONTAP*: Digite o nome de usuário e a senha do ONTAP.
.. *Storage VM credentials* (somente criação avançada): Insira e confirme a senha da VM de armazenamento. A palavra-passe pode ser específica para este sistema de ficheiros ou pode utilizar a mesma palavra-passe introduzida para as credenciais ONTAP.


. Na seção "Anexo do cluster EVS", insira as seguintes informações:
+
.. *Opções de montagem de armazenamento de dados*: Opcionalmente, ative a opção *Montar armazenamentos de dados no cluster EVS* para conectar automaticamente os armazenamentos de dados ao cluster Amazon EVS. Esta opção também faz com que o Workload Factory configure as definições do host VMware ESXi para que correspondam às recomendações de práticas recomendadas do ONTAP . Antes de implantar o sistema de arquivos, você pode revisar os detalhes do plano na seção *Resumo* para ver as configurações que foram alteradas.
.. *Detalhes do console do EVS Cluster vSphere*: insira o endereço IP ou FQDN do servidor VMware vCenter que deve se conectar ao Amazon EVS.
.. *ARN secreto das credenciais do administrador do vSphere*: escolha o ARN secreto para as credenciais do administrador do vSphere.  Essas credenciais são usadas para montar armazenamentos de dados e configurar as configurações recomendadas do VMware.
+
Se o Amazon EVS não estiver disponível nesta região ou se sua conta não tiver permissões para recuperar a lista de ARNs secretos disponíveis, você poderá inserir manualmente um valor de ARN secreto.



. Na seção *Resumo*, você pode visualizar o sistema de arquivos FSX for ONTAP e a configuração de datastore que o consultor de migração da VMware projetou com base em suas informações.
. Selecione *criar* para implantar o sistema de arquivos FSX for ONTAP. Este processo pode levar até 2 horas.
+
Opcionalmente, na janela Codebox, você pode selecionar *Redirecionar para CloudFormation* para criar o sistema de arquivos e a configuração de VM recomendada usando uma pilha do CloudFormation.

+
Em ambos os casos, você pode monitorar o progresso da criação no CloudFormation.





== Resultado

O sistema de arquivos FSX for ONTAP é implantado. Agora você pode usar o modelo do AWS CloudFormation no Codebox para implantar a configuração de VM recomendada no seu ambiente do Amazon Elastic VMware Service.
