---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: Efetue login no NetApp Workload Factory para acessar o centro de planejamento do VMware.  Você pode criar um plano de implantação para o EVS manualmente. 
---
= Crie manualmente um plano de implantação para o Amazon EVS
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Efetue login no NetApp Workload Factory para acessar o centro de planejamento do VMware.  A partir daí, você pode criar manualmente um plano de implantação ou migração para o Amazon EVS personalizado para suas necessidades.

Você pode especificar manualmente seus requisitos para máquinas virtuais no Amazon Elastic VMware Service e usar sistemas de arquivos Amazon FSx for NetApp ONTAP personalizados como armazenamentos de dados externos.



== Requisitos

* Você precisa de um nome de usuário e senha para acessar o Workload Factory.  Se você não tem acesso, crie uma conta agora.  Consulte as instruções. https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["aqui"] .
* Você deve ter uma assinatura do Amazon Elastic VMware Service.




== Passos

. Faça login no Workload Factory usando um dos https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^] .
. Opcionalmente, se você acessou o Workload Factory no console do Workload Factory, no bloco de cargas de trabalho do VMware, selecione *VMware planning center* e, em seguida, selecione *VMware planning center*.  O centro de planejamento do VMware é exibido.
. Selecione *Criar plano EVS manualmente*.
. Insira os requisitos para seu ambiente de VM.
+
[NOTE]
====
Tenha em mente os seguintes requisitos e recomendações de desempenho de migração de VM:

** Uma capacidade mínima de armazenamento de 10 TiB é recomendada para o inventário de VM por motivos de desempenho.
** Uma taxa de transferência mínima é necessária para os armazenamentos de dados do Amazon Elastic VMware Service, dependendo do número necessário de IOPS especificado para esta implantação.
** Dependendo da configuração do sistema de arquivos FSx para ONTAP, um número mínimo de armazenamentos de dados externos é necessário para que o ambiente do Amazon Elastic VMware Service atinja o desempenho ideal.


====
. Quando estiver pronto, selecione *Revisar plano* para revisar o plano de migração.
. Reveja o plano. Expanda cada seção para ver os detalhes do plano.
+
Por padrão, o Workload Factory salva o plano de migração no centro de planejamento.  Você pode desmarcar esta opção perto do topo da página.

. Opcionalmente, você pode exportar o plano de migração como um arquivo PDF ou CSV selecionando *Gerenciar plano* no canto superior direito da página e, em seguida, selecionando *Baixar um relatório (.pdf)* ou *Baixar implantação de armazenamento de VM (.csv)*.
+
O arquivo .csv cria um mapa de todas as VMs incluídas no plano de migração, juntamente com seus volumes de armazenamento atribuídos.

. Quando estiver pronto para provisionar o plano de implantação, selecione *Provisionar*.


link:deploy-fsx-file-system-evs.html["Implante o sistema de arquivos FSX for ONTAP recomendado para cargas de trabalho da VMware"].
