---
sidebar: sidebar 
permalink: learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'O NetApp Workload Factory para VMware fornece ferramentas para mover seus dados de sistemas locais para o Amazon EVS, VMware Cloud on AWS (VMC) ou Amazon EC2.' 
---
= Saiba mais sobre o NetApp Workload Factory para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O NetApp Workload Factory para VMware fornece ferramentas para mover seus dados de sistemas locais para o Amazon Elastic VMware Service (EVS), VMware Cloud on AWS (VMC) ou Amazon EC2.



== O que é o NetApp Workload Factory para VMware?

O NetApp Workload Factory para VMware fornece um centro de planejamento e consultores de migração que permitem analisar suas configurações atuais de máquina virtual em ambientes vSphere locais.  Os consultores de migração então geram um plano para implantar layouts de VM recomendados em clusters Amazon EVS, Amazon EC2 ou VMware Cloud on AWS vSphere e usam sistemas de arquivos Amazon FSx for NetApp ONTAP personalizados como armazenamentos de dados externos.  O centro de planejamento, atuando como o painel do Workload Factory for VMware, permite que você gerencie conjuntos de dados de inventário de VMs salvos e planos de migração salvos, além de provisionar qualquer um dos planos de migração que você salvou.

O Amazon FSx for NetApp ONTAP é um armazenamento de dados NFS externo criado no sistema de arquivos ONTAP da NetApp que pode ser anexado a instâncias do Amazon EVS ou Amazon EC2 ou a clusters do VMware Cloud on AWS vSphere.  Não há necessidade de adicionar mais hosts para aumentar o armazenamento disponível; em vez disso, basta usar o FSx para volumes ONTAP como armazenamentos de dados externos para complementar os armazenamentos de dados vSAN.  Isso fornece uma infraestrutura de armazenamento virtualizada, flexível e de alto desempenho, que pode ser dimensionada independentemente dos recursos de computação.

Para obter mais informações sobre o Workload Factory, consulte o https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["Visão geral da Workload Factory"^] .



== Como funcionam os consultores de migração da VMware

Os consultores de migração podem ajudar você a mover máquinas virtuais (VMs) locais e seus dados, em execução em qualquer datastores com suporte da VMware, para datastores Amazon EVS, Amazon EC2 ou VMware Cloud, o que inclui datastores NFS suplementares em um sistema de arquivos FSx para ONTAP .

Observe que você pode anexar até quatro (4) volumes do FSX for ONTAP a um único cluster do vSphere no VMware Cloud na AWS.



== O que você pode fazer com os consultores de migração

Os consultores de migração fornecem as seguintes funcionalidades:

* Analise as configurações atuais de VM no local
* Determine quais VMs migrar para o Amazon EC2, Amazon EVS ou VMware Cloud na AWS
* Identifique o espaço necessário no FSX para volumes do ONTAP para ser usado como datastores externos de VM
* Revise o relatório resultante para entender as etapas de implantação
* Execute a implantação real


O consultor de migração oferece suporte ao planejamento de configuração para uma única instância do Amazon EVS ou Amazon EC2 ou cluster do VMware Cloud on AWS conectado a um único sistema de arquivos FSx para ONTAP .



== Benefícios de usar consultores de migração

A transição de partes da sua infraestrutura atual para o Amazon EC2 ou VMware Cloud na AWS usando o Amazon FSX for ONTAP como datastores NFS externos oferece os seguintes benefícios:

* Otimização dos custos devido à desacoplamento do host e do storage e à eficiência avançada de dados
* Capacidade de aumentar a capacidade de storage conforme necessário sem a necessidade de adquirir instâncias de host adicionais
* Funcionalidades de gerenciamento de dados da NetApp ONTAP na nuvem, como snapshots com uso eficiente de espaço, clonagem, compressão, deduplicação, compactação e replicação
* Redução no gerenciamento de atualizações de hardware
* Capacidade de alterar a taxa de transferência de dados, IOPS e o tamanho do sistema de arquivos, além de aumentar ou diminuir o tamanho dos volumes
* Alta disponibilidade com suporte para implantações de várias zonas de disponibilidade (AZ)
* Redução de custo e latência de configurações de uma única AZ que usam peering VPC sem exigir um Transit Gateway




== Ferramentas para usar o NetApp Workload Factory

Você pode usar o NetApp Workload Factory com as seguintes ferramentas:

* *Console do Workload Factory*: O console do Workload Factory fornece uma visão visual e holística de seus aplicativos e projetos.
* * NetApp Console*: O NetApp Console oferece uma experiência de interface híbrida para que você possa usar o Workload Factory junto com outros serviços de dados do NetApp .
* *Pergunte-me*: use o assistente de IA Ask me para fazer perguntas e saber mais sobre o Workload Factory sem sair do console do Workload Factory. Acesse Pergunte-me no menu de ajuda do Workload Factory.
* *CloudShell CLI*: O Workload Factory inclui um CloudShell CLI para gerenciar e operar ambientes AWS e NetApp em todas as contas a partir de um único CLI baseado em navegador. Acesse o CloudShell na barra superior do console do Workload Factory.
* *API REST*: Use as APIs REST do Workload Factory para implantar e gerenciar seu FSx para sistemas de arquivos ONTAP e outros recursos da AWS.
* *CloudFormation*: use o código do AWS CloudFormation para executar as ações definidas no console do Workload Factory para modelar, provisionar e gerenciar recursos da AWS e de terceiros da pilha do CloudFormation na sua conta da AWS.
* *Provedor do Terraform NetApp Workload Factory*: use o Terraform para criar e gerenciar fluxos de trabalho de infraestrutura gerados no console do Workload Factory.




== Custo

Não há custo para usar o Workload Factory para VMware.

Você precisará pagar pelos recursos da AWS que implantar com base nas recomendações dos consultores de migração.



== Licenciamento

Não são necessárias licenças especiais da NetApp para usar o Workload Factory para VMware.



== Regiões

O Workload Factory é suportado em todas as regiões comerciais onde o FSx for ONTAP é suportado. https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Veja as regiões da Amazon suportadas."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem Secreta
* Nuvem Top Secret

