---
sidebar: sidebar 
permalink: migrate-data.html 
keywords: vm workloads, fsx for ontap, migration, data migration, vmware hcx 
summary: Use uma ferramenta como o VMware Hybrid Cloud Extension para mover seus dados do antigo armazenamento de máquina virtual para o FSX for NetApp ONTAP volumes conectados às novas máquinas virtuais. A funcionalidade de núcleo do VMware HCX permite migrar cargas de trabalho do data center local para o SDDC de forma transparente. 
---
= Migre seus dados para a nova infraestrutura com a fábrica de workloads da BlueXP  para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Use uma ferramenta como O VMware Hybrid Cloud Extension (HCX) para mover seus dados do armazenamento antigo da máquina virtual para o FSX for NetApp ONTAP volumes conetados às suas novas máquinas virtuais. A funcionalidade de núcleo do VMware HCX permite migrar cargas de trabalho do data center local para o data center definido por software (SDDC) de forma transparente.

https://docs.vmware.com/en/VMware-Cloud-on-AWS/services/com.vmware.vmc-aws-operations/GUID-E8671FC6-F64B-4D41-8F01-B6120B0E3675.html["Revise a documentação do VMware HCX"^] para mais detalhes.

.O que se segue?
Agora que você migrou seus dados para o VMware Cloud no AWS e o Amazon FSX for NetApp ONTAP armazenamentos externos, você pode fazer backup e proteger os dados importantes no seu sistema de arquivos FSX for ONTAP para garantir que seus dados estejam sempre disponíveis.

Para obter informações sobre como gerenciar seu sistema de arquivos FSX for ONTAP, acesse https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Documentação do Amazon FSX para NetApp ONTAP"] para ver os recursos de backup e proteção que você pode usar.
