---
sidebar: sidebar 
permalink: migrate-data-native.html 
keywords: vm workloads, fsx for ontap, migration, data migration, vmware hcx 
summary: 'Use uma ferramenta como o AWS Application Migration Service (MGN) para mover seus dados do armazenamento antigo da máquina virtual para o FSX for NetApp ONTAP volumes conetados às suas novas máquinas virtuais.' 
---
= Migre seus dados para a nova infraestrutura
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Use uma ferramenta como o AWS Application Migration Service (MGN) para mover seus dados do armazenamento antigo da máquina virtual para o FSX for NetApp ONTAP volumes conetados às suas novas máquinas virtuais.

O AWS MGN permite que você migre seus aplicativos para o FSX for NetApp ONTAP volumes no Amazon EC2.

https://docs.aws.amazon.com/mgn/latest/ug/what-is-application-migration-service.html["Revise a documentação do AWS Application Migration Service"^] para mais detalhes.

.O que se segue?
Agora que você migrou seus dados para os datastores externos da AWS e do Amazon FSX for NetApp ONTAP, você pode fazer backup e proteger os dados importantes no seu sistema de arquivos FSX for ONTAP para garantir que seus dados estejam sempre disponíveis.

Para obter informações sobre como gerenciar seu sistema de arquivos FSX for ONTAP, acesse https://docs.netapp.com/us-en/workload-fsx-ontap/index.html["Documentação do Amazon FSX para NetApp ONTAP"] para ver os recursos de backup e proteção que você pode usar.
