---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de workloads da VMware
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre o NetApp Workload Factory para VMware
      url: "/learn-about-vmware-workloads.html"
    - title: Início rápido para migração para o Amazon EVS
      url: "/quick-start-evs.html"
    - title: Início rápido para migrar para o Amazon EC2
      url: "/quick-start-native.html"
    - title: Início rápido para migrar para o VMware Cloud na AWS
      url: "/quick-start.html"
    - title: Explore o centro de planejamento da VMware
      url: "/explore-planning-center.html"
  - title: Use o centro de planejamento da VMware
    entries:
    - title: Carregar dados de inventário de VM
      url: "/upload-vm-inventory.html"
    - title: Migrar para o Amazon Elastic VMware Service
      entries:
      - title: Explorar economias
        url: "/calculate-evs-savings.html"
      - title: Criar manualmente um plano de implantação
        url: "/launch-migration-advisor-evs-manual.html"
      - title: Crie um plano de implantação usando o consultor de migração
        url: "/launch-migration-advisor-evs.html"
      - title: Implante o sistema de arquivos FSX for ONTAP recomendado
        url: "/deploy-fsx-file-system-evs.html"
    - title: Migrar para o Amazon EC2
      entries:
      - title: Crie um plano de implantação usando o consultor de migração
        url: "/launch-onboarding-advisor-native.html"
      - title: Implante o sistema de arquivos FSX for ONTAP recomendado
        url: "/deploy-fsx-file-system-native.html"
    - title: Migre para o VMware Cloud na AWS
      entries:
      - title: Crie um plano de implantação usando o consultor de migração
        url: "/launch-onboarding-advisor.html"
      - title: Implante o sistema de arquivos FSX for ONTAP recomendado
        url: "/deploy-fsx-file-system.html"
      - title: Conete o FSX for ONTAP ao VMware Cloud na AWS
        url: "/connect-sddc-to-fsx.html"
      - title: Migre seus dados para a nova infraestrutura
        url: "/migrate-data.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/support-registration.html"
    - title: Obtenha ajuda
      url: "/get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
