---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Saiba o que há de novo com o componente VMware Migration Advisor do Workload Factory. 
---
= O que há de novo
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo com o componente consultor de migração do VMware Cloud do Workload Factory.



== 19 de setembro de 2024



=== Aprimoramentos do VMware Migration Advisor

Esta versão do Workload Factory for VMware apresenta melhorias de funcionalidade e estabilidade, bem como a capacidade de importar e exportar planos de migração ao usar o consultor de migração da VMware.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 1 de setembro de 2024



=== Migrar para o Amazon EC2

O Workload Factory para VMware agora oferece suporte à migração para o Amazon EC2 usando o consultor de migração da VMware.



== 7 de julho de 2024



=== Lançamento inicial do Workload Factory para VMware

A versão inicial inclui a capacidade de usar o consultor de migração da VMware para analisar as configurações atuais da máquina virtual em ambientes vSphere locais e gerar um plano para implantar layouts de VM recomendados no VMware Cloud na AWS e usar sistemas de arquivos personalizados do Amazon FSX for NetApp ONTAP como datastores externos.
