---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: Saiba o que há de novo no componente VMware Migration Advisor do Workload Factory. 
---
= Novidades do NetApp Workload Factory para VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo no componente VMware Migration Advisor do Workload Factory.



== 2 de novembro de 2025



=== Apresentando as preferências do Amazon Elastic VMware Service no assistente de implantação do sistema de arquivos FSx para ONTAP .

Ao implantar um sistema de arquivos FSx para ONTAP para ser usado como armazenamento de dados NFS externo para o Amazon Elastic VMware Service, agora você pode selecionar o ambiente EVS ao qual os armazenamentos de dados serão conectados.  Isso preenche automaticamente vários campos no assistente de implantação para simplificar o processo de implantação.

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["Implante o sistema de arquivos FSX for ONTAP recomendado"]



=== Alterações de permissões para cargas de trabalho do VMware

As cargas de trabalho da VMware oferecem mais clareza sobre as permissões necessárias para ações específicas e granularidade para selecionar apenas as permissões de que você precisa.  Ao adicionar credenciais, você terá duas opções de permissões para escolher, em vez do modelo de permissões anterior, que era _somente leitura_ e _leitura/gravação_. O novo modelo de permissões divide as políticas de permissão da seguinte forma:

* _Visualização, planejamento e análise_: Visualize o inventário de ambientes de virtualização da EVS, obtenha uma análise bem arquitetada para seus sistemas e explore oportunidades de economia.
* _Implantação e conectividade do armazenamento de dados_: Implante os layouts de VM recomendados em clusters Amazon EVS, Amazon EC2 ou VMware Cloud on AWS vSphere e use sistemas de arquivos Amazon FSx for NetApp ONTAP como armazenamentos de dados externos.


Ao adicionar credenciais, você pode selecionar uma ou mais dessas políticas de permissão com base no nível de acesso que deseja fornecer às cargas de trabalho do VMware.

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Referência de permissões do Workload Factory"^]



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do NetApp Workload Factory para VMware apresenta diversas melhorias na experiência do consultor de migração:

* *Salvar ou baixar um plano de migração*: Agora você pode salvar ou baixar um plano de migração como um arquivo PDF ou CSV.  Ao salvar um plano de migração, o plano é salvo em sua conta do Workload Factory.




== 5 de outubro de 2025



=== BlueXP workload factory agora NetApp Workload Factory

O BlueXP foi renomeado e redesenhado para refletir melhor o papel que ele tem no gerenciamento da sua infraestrutura de dados. Como resultado, a BlueXP workload factory foi renomeada para NetApp Workload Factory.



=== Apresentando o centro de planejamento de cargas de trabalho da VMware

O centro de planejamento de cargas de trabalho da VMware permite que você visualize e gerencie seu inventário de VMs e planos de migração em um só lugar.  Você pode carregar e salvar vários inventários de VMs de diferentes ambientes e começar a planejar uma migração para o serviço AWS EC2 ou Amazon Elastic VMware para qualquer um deles.  Você também pode criar e salvar planos de migração do AWS EC2 ou EVS.

https://docs.netapp.com/us-en/workload-vmware/explore-planning-center.html["Explore o centro de planejamento de cargas de trabalho da VMware"]



=== Apresentando o suporte do consultor de migração para o Amazon Elastic VMWare Service

O BlueXP Workload Factory para VMware agora permite que você use o consultor de migração do Amazon Elastic VMware Service para migrar rapidamente suas cargas de trabalho VMware locais para o Amazon Elastic VMware Service.  Depois de criar um plano de migração usando o consultor de migração, ele é salvo automaticamente na lista de planos de migração no centro de planejamento.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs.html["Crie um plano de implantação para o Amazon EVS usando o consultor de migração"]



== 3 de agosto de 2025



=== Suporte aprimorado do consultor de migração para o Amazon Elastic VMWare Service

O NetApp Workload Factory agora oferece suporte à implantação e montagem automáticas do seu sistema de arquivos Amazon FSx for NetApp ONTAP .  Isso permite que você comece a implantar suas VMs no FSx para sistemas de arquivos ONTAP quando a migração para o ambiente Amazon EVS estiver concluída.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Crie um plano de implantação para o Amazon EVS usando o consultor de migração"]



=== Calcule a economia de custos da migração para o Amazon Elastic VMware Service

Agora você pode explorar as possíveis economias ao migrar suas cargas de trabalho do VMware para o Amazon Elastic VMware Service (EVS).  A calculadora de economia permite que você compare os custos de uso do Amazon EVS com e sem o Amazon FSx for NetApp ONTAP como armazenamento subjacente.  A calculadora exibe potenciais economias em tempo real à medida que você ajusta as características do seu ambiente.

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["Explore as economias do Amazon Elastic VMware Service com o BlueXP Workload Factory"]



== 29 de junho de 2025



=== Apresentando o suporte do consultor de migração para o Amazon Elastic VMWare Service

O BlueXP Workload Factory para VMware agora oferece suporte ao Amazon Elastic VMware Service. Você pode migrar manualmente suas cargas de trabalho VMware locais para o Amazon Elastic VMware Service, otimizando custos e permitindo mais controle sobre seu ambiente VMware sem precisar refatorar ou reestruturar seus aplicativos.

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["Crie um plano de implantação para o Amazon EVS usando o consultor de migração"]



== 4 de maio de 2025



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do BlueXP Workload Factory para VMware apresenta a seguinte melhoria na experiência do consultor de migração do Amazon EC2:

*Insights de infraestrutura de dados da NetApp como fonte de dados*: A fábrica de carga de trabalho agora se coneta diretamente com os insights de infraestrutura de dados da NetApp para coletar informações de implantação da VMware quando você usa o coletor de dados do consultor de migração do EC2.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



=== Terminologia de permissões atualizada

A interface do usuário e a documentação do Workload Factory agora usam "somente leitura" para se referir às permissões de leitura e "leitura/gravação" para se referir às permissões de automação.



== 30 de março de 2025



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do BlueXP Workload Factory para VMware apresenta diversas melhorias na experiência do consultor de migração do Amazon EC2:

* *Orientação aprimorada de atribuição de volume*: As informações de atribuição de volume nas etapas "Classify" e "Package" do consultor de migração do EC2 apresentam maior legibilidade e usabilidade. Mais informações úteis são exibidas sobre cada volume, permitindo que você identifique melhor os volumes e determine como atribuí-los.
* *Melhorias na eficiência do script do coletor de dados*: O script do coletor de dados do consultor de migração do EC2 otimiza o uso da CPU ao coletar dados para implantações menores de VM.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 2 de março de 2025



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do BlueXP Workload Factory para VMware apresenta diversas melhorias na experiência do consultor de migração do Amazon EC2:

* *Tipo de instância estimado*: O Migration Advisor agora pode examinar os requisitos do seu ambiente e fornecer um tipo de instância estimado do Amazon EC2 para cada VM. Você pode optar por incluir o tipo de instância estimado para cada VM durante a etapa de escopo do consultor de migração.
* * Capacidade de recomendar volumes do Amazon EBS*: O consultor de migração agora pode recomendar a migração de volumes de dados para o Amazon Elastic Block Store (EBS) em vez do Amazon FSX for NetApp ONTAP devido a necessidades específicas de capacidade ou desempenho de uma determinada região.
* * Atribuição automática de sistema de arquivos aprimorada*: A atribuição de sistema de arquivos do Amazon FSX for NetApp ONTAP foi melhorada para otimizar melhor o custo e minimizar o throughput.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 5 de janeiro de 2025



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do BlueXP Workload Factory para VMware apresenta diversas melhorias na experiência do consultor de migração:

* *Salvar ou baixar um plano de migração*: Agora você pode salvar ou baixar um plano de migração e carregá-lo para preencher o consultor de migração.  Quando você salva um plano de migração, o plano é salvo com sua conta do Workload Factory.
* *Seleção de VM aprimorada*: o BlueXP Workload Factory para VMware agora oferece suporte à filtragem e pesquisa da lista de VMs que você deseja incluir na sua implantação de migração.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 1 de dezembro de 2024



=== Melhorias do consultor de migração do Amazon EC2

Esta versão do NetApp Workload Factory para VMware apresenta diversas melhorias na experiência do consultor de migração:

* *Coleta de dados*: O BlueXP Workload Factory para VMware oferece suporte à capacidade de coletar dados por um período específico quando você usa o consultor de migração.
* *Seleção de VM*: O BlueXP Workload Factory para VMware agora oferece suporte à seleção de VMs que você deseja incluir na sua implantação de migração.
* * Experiência rápida vs. Avançada*: Quando você usa o consultor de migração, agora você pode escolher uma experiência de migração rápida, usando RVtools, ou a experiência avançada, que usa o coletor de dados do consultor de migração.


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 3 de novembro de 2024



=== Ajuda da taxa de redução de dados do consultor de migração da VMware

Esta versão do Workload Factory for VMware apresenta um assistente de taxa de redução de dados. O assistente de taxa de redução de dados ajuda você a decidir qual é a melhor proporção para seu inventário e armazenamento da VMware ao se preparar para a integração na nuvem da AWS.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 19 de setembro de 2024



=== Aprimoramentos do VMware Migration Advisor

Esta versão do Workload Factory para VMware apresenta melhorias de funcionalidade e estabilidade, bem como a capacidade de importar e exportar planos de migração ao usar o consultor de migração do VMware.

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["Crie um plano de implantação para o Amazon EC2 usando o consultor de migração"]



== 1 de setembro de 2024



=== Migrar para o Amazon EC2

A fábrica de workloads para VMware agora oferece suporte à migração para o Amazon EC2 usando o consultor de migração da VMware.



== 7 de julho de 2024



=== Lançamento inicial do Workload Factory para VMware

A versão inicial inclui a capacidade de usar o consultor de migração da VMware para analisar as configurações atuais da máquina virtual em ambientes vSphere locais e gerar um plano para implantar layouts de VM recomendados no VMware Cloud na AWS e usar sistemas de arquivos personalizados do Amazon FSX for NetApp ONTAP como datastores externos.
